/*
Author: Aryaman Kejriwal
Course: Introduction to Programming in C
instructor: Gilbert Pajela
Assignment: Lab 6.4

This program tests a function that returns as follows:

        _
       |0              x <= 0
f(x) = |
       |f(x-1) + 2     x > 0
        -

The number generated by this recursive method is 2 times the number inputted.

f(x) == g(x) if g(x) = 2 * x
*/

#include <stdio.h>

double f(double x);

int main() {
  double x = 0;

  printf("Enter value of x> ");
  scanf("%lf", &x);

  double ans = f(x);

  printf("The value of f(x) is %lf.\n", ans);
  return(0);
}

//f(x) returns 2 * x
double f(double x) {
  if(x <= 0) {
    return(0);
  } else {
    return(f(x-1) + 2);
  }
}
